StarRocks/starrocks-connector-for-apache-spark

- src/main/java/com/starrocks/connector/spark/rest/RestService.java
fix #1 
By default, httpclient will not provide credentials preemptively,
it will first create a HTTP request without authentication parameters.
This is by design, as a security precaution, and as part of the spec.
But it causes extra latency to a request, as you need to make multiple calls,
and causes errors to appear in the logs.
So we can use the preemptive basic authentication to avoid useless http
request without authentication.
> Bugfix: use preemptive basic authentication to avoid useless http request without authentication

- .gitignore
- .idea/.gitignore
- pom.xml
- src/main/java/com/starrocks/connector/spark/serialization/RowBatch.java
- src/main/java/com/starrocks/connector/spark/util/DataTypeUtils.java
- src/main/scala/com/starrocks/connector/spark/sql/SchemaUtils.scala
Signed-off-by: xlfjcg <1937532871@qq.com>
> [BugFix] Read starrocks table data out-of-order

- src/main/java/com/starrocks/connector/spark/sql/conf/StarRocksConfig.java
- src/main/java/com/starrocks/connector/spark/sql/conf/WriteStarRocksConfig.java
- src/main/java/com/starrocks/connector/spark/sql/schema/InferSchema.java
Fix bug for spark dataframe write
> [Bugfix] Fix spark dataframe write 

- src/main/java/com/starrocks/connector/spark/sql/write/StarRocksDataWriter.java
Fixes 
Because we use `StreamLoadManagerV2` instead of `DefaultStreamLoadManager` which could commit automatically even if using transaction stream load, so there is no need to commit after flush
> [Enhancement] StreamLoadManager don't need to commit after flush

- src/main/java/com/starrocks/connector/spark/sql/StarRocksTableProvider.java
- src/main/java/com/starrocks/connector/spark/sql/conf/StarRocksConfigBase.java
- src/main/scala/com/starrocks/connector/spark/sql/Utils.scala
- src/test/java/com/starrocks/connector/spark/sql/ReadITTest.java
- src/test/java/com/starrocks/connector/spark/sql/SchemaITTest.java
- src/test/java/com/starrocks/connector/spark/sql/WriteITTest.java
Fixes #
`starrocks.fe.http.url`  is more understandable than `starrocks.fenodes`. `starrocks.fenodes` is still valid if the user sets it so that we can keep compatible with read
> [Enhancement] Replace starrocks.fenodes with starrocks.fe.http.url 

- pom.xml
Fixes #
Don't shade google common and apache common package because they are provided by spark
> [Bugfix] Don't shade google common and apache common package

- build.sh
- pom.xml
> [Enhancement] Refine the build script

- src/main/java/com/starrocks/connector/spark/sql/conf/WriteStarRocksConfig.java
> [Enhancement] Set stream load timeout according to flush interval

- pom.xml
> [Feature] Add distributionManagement to deploy the jar

- src/main/java/com/starrocks/connector/spark/sql/conf/StarRocksConfigBase.java
- src/main/java/com/starrocks/connector/spark/sql/conf/WriteStarRocksConfig.java
- src/test/java/com/starrocks/connector/spark/sql/WriteITTest.java
> [Enhancement] Support to configure bytes with unit

- src/main/java/com/starrocks/connector/spark/sql/conf/WriteStarRocksConfig.java
- src/main/java/com/starrocks/connector/spark/sql/schema/StarRocksField.java
- src/main/java/com/starrocks/connector/spark/sql/schema/StarRocksSchema.java
- src/main/scala/com/starrocks/connector/spark/sql/Utils.scala
> [Feature] Support upsert/delete/partial update for primary key table

- pom.xml
- src/main/java/com/starrocks/connector/spark/sql/connect/StarRocksConnector.java
- src/test/java/com/starrocks/connector/spark/examples/SimpleWrite.java
- src/test/java/com/starrocks/connector/spark/sql/WriteITTest.java
- src/test/resources/simple_write_csv/test.csv
> [Feature] Add simple examples

- pom.xml
- src/main/java/com/starrocks/connector/spark/sql/write/StarRocksDataWriter.java
- src/main/java/com/starrocks/connector/spark/sql/write/StarRocksWriterFactory.java
- src/main/java/com/starrocks/connector/spark/util/EnvUtils.java
> [Feature] Add git-commit-id-plugin

- pom.xml
> [Enhancement] Add nexus-staging-maven-plugin for deploy

- pom.xml
> [Enhancement] Add project information to pom

- pom.xml
> [Feature] Add gpg plugin

- pom.xml
> [Enhancement] Add maven-javadoc-plugin and maven-source-plugin

- pom.xml
> Bump version to 1.1.1-SNAPSHOT

- pom.xml
> Bump version to 1.1-SNAPSHOT

- pom.xml
> [Enhancement] Remove scala dependency

- pom.xml
> [Refactor] Use three versions for snapshot

- pom.xml
- src/main/java/com/starrocks/connector/spark/sql/schema/AbstractRowStringConverter.java
- src/main/java/com/starrocks/connector/spark/sql/schema/InternalRowToRowFunction.java
- src/main/java/com/starrocks/connector/spark/sql/schema/JSONRowStringConverter.java
- src/main/java/com/starrocks/connector/spark/sql/write/StarRocksDataWriter.java
- src/main/java/com/starrocks/connector/spark/sql/write/StarRocksWrite.java
- src/main/java/com/starrocks/connector/spark/sql/write/StarRocksWriteBuilder.java
- src/main/java/com/starrocks/connector/spark/sql/write/StarRocksWriterFactory.java
- src/test/java/com/starrocks/connector/spark/sql/SchemaITTest.java
Fixes #
replace fastjson with jackson so that we can reuse the jackson jar provided by spark
> [Enhancement] Replace fastjson with jackson

- src/main/java/com/starrocks/connector/spark/sql/conf/WriteStarRocksConfig.java
- src/test/java/com/starrocks/connector/spark/sql/WriteITTest.java
> [Feature] Support to retry for write

- src/test/java/com/starrocks/connector/spark/examples/PrimaryKeyWrite.java
> [Enhancement] Add example for partial update of primary key

- src/main/java/com/starrocks/connector/spark/rest/RestService.java
- src/test/java/com/starrocks/connector/spark/sql/ConfigurationITTest.java
- src/test/java/com/starrocks/connector/spark/sql/ITTestBase.java
> [Enhancement] starrocks.fe.http.url supports to add http scheme

- docs/connector-write.md
> [Doc] Add doc for loading bitmap/hll data

- src/test/java/com/starrocks/connector/spark/sql/ConfigurationITTest.java
- src/test/java/com/starrocks/connector/spark/sql/ITTestBase.java
- src/test/java/com/starrocks/connector/spark/sql/ReadWriteITTest.java
- src/test/java/com/starrocks/connector/spark/sql/StructuredStreamingITTest.java
> [Doc] Add test for conditional update

- docs/connector-write.md
> [Doc] Add document for loading array data

- src/main/java/com/starrocks/connector/spark/exception/StarrocksException.java
- src/main/java/com/starrocks/connector/spark/sql/StarRocksTable.java
- src/main/java/com/starrocks/connector/spark/sql/conf/WriteStarRocksConfig.java
- src/main/java/com/starrocks/connector/spark/sql/connect/StarRocksConnector.java
- src/main/java/com/starrocks/connector/spark/sql/schema/StarRocksSchema.java
> [Enhancement] Add privilege and parameter check hint in error log

- src/test/java/com/starrocks/connector/spark/sql/StructuredStreamingITTest.java
> [UT] Use TemporaryFolder rule to create and cleanup test directory

- docs/connector-read.md
- docs/connector-write.md
> [Doc] Add privilege requirement notice

- pom.xml
> Bump version to 1.1.2-SNAPSHOT

- build.sh
- pom.xml
- src/main/java/com/starrocks/connector/spark/sql/schema/InternalRowToRowFunction.java
> [Enhancement] Support Apache Spark 3.5.0

- src/main/java/com/starrocks/connector/spark/exception/ConnectedFailedException.java
- src/main/java/com/starrocks/connector/spark/rest/RestService.java
> [Enhancement] RestService logs response status and entity for debug

- src/test/java/com/starrocks/connector/spark/sql/ITTestBase.java
- src/test/java/com/starrocks/connector/spark/sql/ReadWriteITTest.java
> [UT] add output col names test

- src/main/java/com/starrocks/connector/spark/rest/models/Field.java
- src/main/java/com/starrocks/connector/spark/serialization/RowBatch.java
- src/main/java/com/starrocks/connector/spark/sql/connect/StarRocksConnector.java
- src/main/scala/com/starrocks/connector/spark/sql/SchemaUtils.scala
- src/test/java/com/starrocks/connector/spark/sql/ITTestBase.java
- src/test/java/com/starrocks/connector/spark/sql/ReadWriteITTest.java
- src/test/scala/com/starrocks/connector/spark/sql/TestSchemaUtils.scala
StarRocks supports conversion from JSON type to Arrow String type in [25044](https://github.com/StarRocks/starrocks/pull/25044) , so connector can support read StarRocks json column to Spark string now
> [Enhancement] Support to read json column

- docs/connector-read.md
- docs/connector-write.md
> [Doc] Add doc for coming version 1.1.2

- src/main/java/com/starrocks/connector/spark/sql/conf/WriteStarRocksConfig.java
- src/main/java/com/starrocks/connector/spark/sql/schema/JSONRowStringConverter.java
- src/main/java/com/starrocks/connector/spark/sql/schema/StarRocksField.java
- src/main/java/com/starrocks/connector/spark/sql/write/StarRocksDataWriter.java
- src/test/java/com/starrocks/connector/spark/sql/ITTestBase.java
- src/test/java/com/starrocks/connector/spark/sql/ReadWriteITTest.java
> [BugFix] Fix write json type incorrectly

- src/main/java/com/starrocks/connector/spark/serialization/RpcRowBatch.java
- src/main/java/com/starrocks/connector/spark/sql/schema/AbstractRowStringConverter.java
- src/test/java/com/starrocks/connector/spark/sql/ReadWriteITTest.java
> [Enhancement] Support to read and write StarRocks DATETIME with microsecond

- src/main/java/com/starrocks/connector/spark/rest/RestService.java
- src/main/java/com/starrocks/connector/spark/sql/schema/JSONRowStringConverter.java
- src/main/java/com/starrocks/connector/spark/util/JsonUtils.java
> [Enhancement] Enlarge max string length of jackson-core

- docs/connector-read.md
- docs/connector-write.md
> [Doc] Add doc for v1.1.3

- pom.xml
> Bump version to 1.1.4-SNAPSHOT

- deploy.sh
> [Tool] support to deploy spark 3.5

- SECURITY.md
Fixes #134 
This PR aims to enhance security, which is necessary for the project's sustainable development.
> [INF]Add security policy

- .github/workflows/ci-pipeline.yml
- build.sh
- common.sh
- deploy.sh
- pom.xml
- src/main/java/com/starrocks/connector/spark/sql/StarRocksDataSourceProvider.java
- src/test/java/com/starrocks/connector/spark/rest/models/SchemaTest.java
- src/test/java/com/starrocks/connector/spark/sql/BypassModeTestBase.java
- src/test/java/com/starrocks/connector/spark/sql/CatalogTest.java
- src/test/java/com/starrocks/connector/spark/sql/ExpectedExceptionTest.java
- src/test/java/com/starrocks/connector/spark/sql/ITTestBase.java
- src/test/java/com/starrocks/connector/spark/sql/ReadWriteITTest.java
> [Tool] Add CI workflow
